export const columns = [
  { key: 'checkbox', title: '', width: 40, minWidth: 40, type: 'custom', sticky: 'left' },
  { key: 'employeeCode', title: 'Mã nhân viên', width: 110, minWidth: 80 },
  { key: 'employeeName', title: 'Tên nhân viên', width: 160, minWidth: 120 },
  { key: 'taxCode', title: 'Mã số thuế', width: 120, minWidth: 90 },
  { key: 'position', title: 'Chức danh', width: 130, minWidth: 100 },
  {
    key: 'bankCode',
    title: 'Số tài khoản',
    width: 130,
    minWidth: 100,
    render: (_, row) => row.banks?.[0]?.bankCode ?? '',
  },
  {
    key: 'bankName',
    title: 'Tên ngân hàng',
    width: 130,
    minWidth: 100,
    render: (_, row) => row.banks?.[0]?.bankName ?? '',
  },
  {
    key: 'status',
    title: 'Trạng thái',
    width: 110,
    minWidth: 90,
    render: (_, row) => (row.status === 'ACTIVE' ? 'Đang sử dụng' : 'Ngừng sử dụng'),
  },
  { key: 'phone', title: 'Số điện thoại', width: 120, minWidth: 100 },
  {
    key: 'gender',
    title: 'Giới tính',
    width: 70,
    minWidth: 60,
    render: (_, row) => (row.gender ? 'Nam' : 'Nữ'),
  },
  { key: 'dob', title: 'Ngày sinh', width: 110, minWidth: 90, dataType: 'date' },
  { key: 'passport', title: 'Hộ chiếu', width: 120, minWidth: 90 },
  { key: 'identity', title: 'CCCD/CMND', width: 140, minWidth: 110 },
  { key: 'issueDate', title: 'Ngày cấp', width: 110, minWidth: 90, dataType: 'date' },
  { key: 'issuePlace', title: 'Nơi cấp', width: 130, minWidth: 100 },
  { key: 'isCustomer', title: 'khách hàng', width: 70, minWidth: 60, type: 'custom' },
  { key: 'isSupplier', title: 'nhà cung cấp', width: 70, minWidth: 60, type: 'custom' },
  { key: 'createdDate', title: 'Ngày tạo', width: 110, minWidth: 90, dataType: 'datetime' },
  { key: 'createdBy', title: 'Người tạo', width: 110, minWidth: 90 },
  { key: 'modifiedDate', title: 'Ngày sửa', width: 110, minWidth: 90, dataType: 'datetime' },
  { key: 'modifiedBy', title: 'Người sửa', width: 110, minWidth: 90 },
  { key: 'baseSalary', title: 'Lương cơ bản', width: 130, minWidth: 100 },
  {
    key: 'salaryCoefficient',
    title: 'Hệ số lương',
    width: 110,
    minWidth: 90,
    dataType: 'number',
    decimal: 2,
  },
  { key: 'insuranceSalary', title: 'Lương bảo hiểm', width: 140, minWidth: 110 },
  { key: 'numberOfDependents', title: 'Số người phụ thuộc', width: 130, minWidth: 100 },
  { key: 'address', title: 'Địa chỉ', width: 180, minWidth: 130 },
  { key: 'fixedPhone', title: 'Điện thoại cố định', width: 130, minWidth: 100 },
  { key: 'email', title: 'Email', width: 160, minWidth: 120 },
  {
    key: 'departmentCode',
    title: 'Mã đơn vị',
    width: 120,
    minWidth: 90,
    render: (_, row) => row.department?.departmentCode ?? '',
  },
  {
    key: 'departmentName',
    title: 'Tên phòng ban',
    width: 150,
    minWidth: 110,
    render: (_, row) => row.department?.departmentName ?? '',
  },
  {
    key: 'receivableAccountCode',
    title: 'TK phải thu',
    width: 120,
    minWidth: 90,
    render: (_, row) => row.receivableAccount?.accountCode ?? '',
  },
  {
    key: 'payableAccountCode',
    title: 'TK phải trả',
    width: 120,
    minWidth: 90,
    render: (_, row) => row.payableAccount?.accountCode ?? '',
  },
  {
    key: 'contractCode',
    title: 'Mã hợp đồng',
    width: 120,
    minWidth: 90,
    render: (_, row) => row.contract?.contractCode ?? '',
  },
  {
    key: 'partnerCode',
    title: 'Mã đối tác',
    width: 120,
    minWidth: 90,
    render: (_, row) => row.partner?.partnerCode ?? '',
  },
  { key: 'action', title: 'Chức năng', width: 100, minWidth: 100, type: 'custom', sticky: 'right' },
]

export const options = [
  { label: '10 bản ghi trên 1 trang', value: 10 },
  { label: '20 bản ghi trên 1 trang', value: 20 },
  { label: '50 bản ghi trên 1 trang', value: 50 },
  { label: '100 bản ghi trên 1 trang', value: 100 },
]

export const employeeBankcolumns = [
  { key: 'bankCode', title: 'Số tài khoản', width: 40, minWidth: 40, type: 'custom' },
  { key: 'bankName', title: 'Tên ngân hàng', width: 110, minWidth: 80, type: 'custom' },
  { key: 'bankAddress', title: 'Chi nhánh', width: 160, minWidth: 120, type: 'custom' },
  { key: 'bankBranch', title: 'Tỉnh/TP của ngân hàng', width: 160, minWidth: 120, type: 'custom' },
  { key: 'action', title: '', width: 40, minWidth: 40, type: 'custom' },
]
