export const employee = () => ({
  employeeId: null,
  employeeCode: '',
  employeeName: '',
  taxCode: '',
  position: '',
  status: 'ACTIVE',
  phone: '',
  gender: true,
  dob: null,
  passport: '',
  identity: '',
  issueDate: null,
  issuePlace: '',
  isCustomer: false,
  isSupplier: false,
  departmentId: null,
  contractId: null,
  partnerId: null,
  receivableAccountId: null,
  payableAccountId: null,
  baseSalary: 0,
  salaryCoefficient: 0.0,
  insuranceSalary: 0,
  banks: [],
})
